# Generated by Django 4.1.2 on 2022-10-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='InstagramAccounts',
        ),
    ]
